import React from "react";
import Head from "next/head";
import { useForm } from "react-hook-form";
import axios from "axios";
import {
  FormControl,
  FormLabel,
  FormControlLabel,
  TextField,
  MenuItem,
  Select,
  FormGroup,
  Checkbox,
  Box,
  Button,
  Card,
  InputLabel,
  ButtonBox,
  Container,
  Typography,
  Grid,
  DatePicker,
} from "@mui/material";
import { EmployerHeader } from "../../components/EmployerHeader";
import SearchIcon from "@mui/icons-material/Search";

const findEmployee = () => {
  return (
    <>
      <Head>
        <title>Jobs | Sera Job Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Box
        component="main"
        sx={{
          width: "100%",
          height: "100vh",
          backgroundColor: "background.default",
        }}
      >
        <Grid Container sx={{ width: "100%" }}>
          <Grid item lg={12} md={12} sm={12}>
            <EmployerHeader />
          </Grid>
          <Grid
            item
            lg={12}
            md={12}
            sm={12}
            sx={{
              m: "auto",
              mt: 4,
              width: "65%",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <SearchIcon color="primary" sx={{ mr: 2, mt: 2 }} />
            <TextField
              sx={{ width: "100%" }}
              variant="standard"
              placeholder="Search Emplyee"
            />
          </Grid>

          <Grid
            item
            lg={8}
            md={10}
            sm={12}
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              
              // mb: 10,
              // ml: 15,
            }}
          >
              <Box
                sx={{
                  p: "3%",
                  m: "auto",
                  mt: 4,
                  width: "70%",
                  borderRadius: "10px",
                  border: "1px solid #C4C4C4",
                  textAlign: "center",
                }}
              >
                <Typography variant="h4" color="#D36B00">
                  Find Freelancer
                </Typography>
                <Typography variant="p" color="#42032C">
                  {" "}
                  You can search for freelancers or agencies, and you have the option to search for those who have earned good ratings Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book. It has survived not only five centuries
                </Typography>
              </Box>
          </Grid>
        </Grid>
      </Box>
    </>
  );
};

export default findEmployee;
