import React from 'react';
import Head from "next/head";
import { useForm } from "react-hook-form";
import axios from "axios";
import {
    FormControl,
    FormLabel,
    FormControlLabel,
    TextField,
    MenuItem,
    Select,
    FormGroup,
    Checkbox,
    Box,
    Button,
    Card,
    InputLabel,
    ButtonBox,
    Container,
    Typography,
    Grid,
    DatePicker,
  } from "@mui/material";
import SearchBar from '../../components/searchBar';


const findEmployee = () => {
    return (
        <>
        <Head>
          <title>Jobs | Sera Job Portal</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap"
            rel="stylesheet"
          />
        </Head>
        <Box
        component="main"
        sx={{
          width: "100%",
          height: "auto",
          backgroundColor: "background.default",
          pt: '3%'
        }}
      >

        <SearchBar/>
        <Grid
            item
            lg={9}
            md={6}
            sm={12}
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              mb: 10,
              ml: 15,
            }}
          >

<Box sx={{mt: '3%', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
                <Box sx={{p: '3%',ml: '3%', width: '70%', borderRadius: '10px', border: '1px solid #C4C4C4', textAlign: "center"}}>
                <Typography variant="h4" color="#D36B00">Find Freelancer</Typography>
                  <Typography  variant="p" color="#42032C"> You can search for freelancers or agencies, and you have the option to search for those who have earned one of our Talent Badges.</Typography>
                </Box>
            </Box>

            </Grid>

        </Box>
        </>
    );
    
};

export default findEmployee;