import Head from "next/head";
import Image from "next/image";
import {Box, Grid} from '@mui/material'
import { EmployerHeader } from "../../components/EmployerHeader";

const Employer = () => {
  return (
    <>
      <Head>
        <title>Jobs | Sera Job Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Box
        component="main"
        sx={{
          width: "100%",
          height: "auto",
          backgroundColor: "background.default",
        }}
      >
        <Grid container spacing={3}>
          <Grid item lg={12} sm={12} xl={12} xs={12}>
            <EmployerHeader />
            {/* <EmployeeHeader /> */}
          </Grid>
        </Grid>
      </Box>
    </>
  );
};

export default Employer;
