import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useForm } from "react-hook-form";
import {
  FormControl,
  FormLabel,
  FormControlLabel,
  TextField,
  MenuItem,
  Select,
  FormGroup,
  Checkbox,
  Box,
  Button,
  Card,
  InputLabel,
  ButtonBox,
  Container,
  Typography,
  Grid,
  DatePicker,
  Divider,
} from "@mui/material";
import { EmployerHeader } from "../components/EmployerHeader";
import SearchIcon from "@mui/icons-material/Search";
import axios from "axios";
import cookie from "js-cookie";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import Router from 'next/router'

const findEmployee = () => {
  const [searchValue, setSearchValue] = useState("");
  const [employee, setEmployee] = useState();

  const handleKeyDown = (event) => {
    if (event.key === "Enter") {
      searchEmployee(searchValue);
    }
  };

  const searchEmployee = (searchValue) => {
    const config = {
      headers: {
        Authorization: "Bearer " + cookie.get("token"),
      },
    };

    const usernamekey = {
      firstName: searchValue,
    };

    axios
      .post("https://localhost:44369/api/User/FindEmplyee", usernamekey, config)
      .then(function (res) {
        console.log(res);
        setEmployee(res.data);
      })
      .catch(function (res) {
        console.log(res);
      });
  };

  const directMessageHandler =(e)=>{
    const postUser = e
    Router.push({
      pathname: "/messages",
      query: {postUser}
    })
  }

  return (
    <>
      <Head>
        <title>Jobs | Sera Job Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Box
        component="main"
        sx={{
          width: "100%",
          height: "105vh",
          backgroundColor: "background.default",
        }}
      >
        <Grid container sx={{ width: "100%" }}>
          <Grid item lg={12} md={12} sm={12}>
            <EmployerHeader />
          </Grid>
          <Grid
            item
            lg={6}
            md={6}
            sm={8}
            sx={{
              m: "auto",
              mt: 4,
              width: "65%",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <SearchIcon color="primary" sx={{ mr: 2, mt: 2 }} />
            <TextField
              sx={{ width: "100%" }}
              variant="standard"
              onKeyDown={handleKeyDown}
              placeholder="Search Emplyee"
              value={searchValue}
              onChange={(e) => setSearchValue(e.target.value)}
            />
          </Grid>

          {employee == null ? (
            <Grid
              item
              lg={12}
              md={10}
              sm={12}
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                
                // mb: 10,
                // ml: 15,
              }}
            >
              <Box
                sx={{
                  p: "3%",
                  m: "auto",
                  mt: 4,
                  width: "70%",
                  borderRadius: "10px",
                  backgroundColor: "background.paper",
                  textAlign: "center",
                  boxShadow: "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px",
                }}
              >
                <Typography variant="h4" color="primary.main" mb={3}>
                  Find Freelancer
                </Typography>
                <Typography variant="p" color="#42032C">
                  {" "}
                  You can search for freelancers or agencies, and you have the
                  option to search for those who have earned good ratings Lorem
                  Ipsum has been the industry's standard dummy text ever since
                  the 1500s, when an unknown printer took a galley of type and
                  scrambled it to make a type specimen book. It has survived not
                  only five centuries
                </Typography>
              </Box>
            </Grid>
          ) : (
            employee.map((e, i) => (
              <Grid item lg={12} md={12} sm={8}>
                <Box
                  sx={{
                    borderRadius: "10px",
                    backgroundColor: "background.paper",
                    // pt: "5%",
                    width: "60%",
                    m: "auto",
                    height: "auto",
                    boxShadow: "rgba(0, 0, 0, 0.10) 0px 5px 5px",
                  }}
                >
                  <Grid container sx={{ mt: "5%", display: "flex" }}>
                    <Grid
                      item
                      lg={8}
                      md={6}
                      sm={12}
                      sx={{ width: "50%", borderRadius: "10px", p: "5%" }}
                    >
                      <Typography variant="h3" color="text.primary">
                        {e.firstName + ' ' + e.middleName}
                      </Typography>
                      <Typography
                        sx={{ display: "flex", alignItems: "center", mt: "3%" }}
                        variant="caption"
                        color="text.primary"
                      >
                        <LocationOnIcon /> {e.location}
                      </Typography>

                      <Divider sx={{ borderColor: "#C4C4C4", mx: 3, my: 3 }} />
                      <Typography variant="p" color="text.primary">
                        {e.bio}
                      </Typography>

                      <Grid container spacing={5} sx={{ mt: 2 }}>
                        <Grid item xs={2}>
                          <Typography variant="h6" color="text.primary">
                            $50.00
                          </Typography>
                          <Typography variant="p" color="text.secondary">
                            Hourly rate
                          </Typography>
                        </Grid>
                        <Grid item xs={2}>
                          <Typography variant="h6" color="text.primary">
                            23
                          </Typography>
                          <Typography variant="p" color="text.secondary">
                            Jobs
                          </Typography>
                        </Grid>
                        <Grid item xs={2}>
                          <Typography variant="h6" color="text.primary">
                            4.5 /5.0
                          </Typography>
                          <Typography variant="p" color="text.secondary">
                            Rating
                          </Typography>
                        </Grid>
                        <Grid item xs={2}>
                          <Typography variant="h6" color="text.primary">
                            293
                          </Typography>
                          <Typography variant="p" color="text.secondary">
                            Hours worked
                          </Typography>
                        </Grid>
                      </Grid>
                      <Button variant="contained" sx={{ mt: "5%" }} onClick={()=>directMessageHandler(e.userId)}>
                        Direct Message
                      </Button>
                    </Grid>
                    <Grid item lg={4} md={6} sm={12} sx={{ pt: 15 }}>
                      <Typography variant="subtitle1" color="black" my={1}>
                        First Name : {e.firstName}
                      </Typography>
                      <Typography variant="subtitle1" color="black" my={1}>
                        Middle Name : {e.middleName}
                      </Typography>
                      <Typography variant="subtitle1" color="black" my={1}>
                        Last Name : {e.lastName}
                      </Typography>
                      <Typography variant="subtitle1" color="black" my={1}>
                        Sex: {e.sex}
                      </Typography>
                      <Typography variant="subtitle1" color="black" my={1}>
                        Email : {e.email}
                      </Typography>
                      <Typography variant="subtitle1" color="black" my={1}>
                        Age : {e.age}
                      </Typography>
                      <Typography variant="subtitle1" color="black" my={1}>
                        Phone Number : {e.phoneNumber}
                      </Typography>
                      <Typography variant="subtitle1" color="black" my={1}>
                        Educational Level : {e.EducationalLevel}
                      </Typography>
                    </Grid>
                  </Grid>
                </Box>
              </Grid>
            ))
          )}
        </Grid>
      </Box>
    </>
  );
};

export default findEmployee;
