import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { EmployerHeader } from "../components/EmployerHeader";
import { EmployeeHeader } from "../components/EmployeeHeader";
import { Container } from "@mui/system";
import { Box,Grid } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Sera Job Po</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap" rel="stylesheet"/>
      </Head>
      <Box 
        component="main" 
        sx={{
          width: '100%',
          height: 'auto',
          backgroundColor: 'background.default'
        }}>
          <Grid container >


            <Grid 
              item 
              lg={12} 
              sm={12} 
              xl={12} 
              xs={12}>
              <EmployerHeader />
              {/* <EmployeeHeader /> */}
            </Grid>

            <Grid item>

            </Grid>
          </Grid>
      </Box>
    </>
  );
}
