import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { EmployerHeader } from "../components/EmployerHeader";
import { EmployeeHeader } from "../components/EmployeeHeader";
import { Container } from "@mui/system";
import { Box, Grid, Typography } from "@mui/material";
import JobsLeftSide from "../components/JobsLeftSide";
import JobsRightSide from "../components/JobsRightSide";
import Posts from "../components/posts";
import SearchBar from "../components/searchBar";
import PostedJob from "../components/postedJob";
import {useState, useEffect} from 'react'
import axios from 'axios'
const Jobs = () => {

  const [searchValue, setSearchValue] = useState();

  const [jobs, setJobs] = useState([]);


  useEffect(()=>{

    const config ={
      headers: {
        Authorization: "Bearer " + localStorage.getItem("token"),
      }
    }

      axios.get("https://localhost:44369/jobs/getAllJob",config)
      .then(function(res){
        // console.log(res)
        setJobs(res.data)
        // console.log(jobs)
      })
      .catch(function(res){
        console.log(res)
      })
  },[])
  
  console.log(jobs)

  return (
    <>
      <Head>
        <title>Jobs | Sera Job Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Box
        component="main"
        sx={{
          width: "100%",
          height: "auto",
          backgroundColor: "background.default",
        }}
      >
        <Grid container spacing={3}>
          <Grid item lg={12} md={12} sm={12}>
            <EmployerHeader/>
          </Grid>

          <Grid item lg={3} sm={3} sx={{ mt: '1.5%', backgroundColor: 'background.paper', borderRadius: '10px', boxShadow: "rgba(0, 0, 0, 0.10) 0px 5px 5px",}} >
            <JobsLeftSide />
          </Grid>
          <Grid item lg={6} sm={8} sx={{}}>
            <Box
              sx={{
                borderRadius: "10px",
                backgroundColor: "background.paper",
                pr: "5%",
                pt: "5%",
                mr: '3%',
                boxShadow: "rgba(0, 0, 0, 0.10) 0px 5px 5px",
              }}
            >
              <SearchBar setSearchValue={setSearchValue}/>
              <Typography variant="h1" color="black">{searchValue}</Typography>
              {jobs && jobs.map((job)=>(
                <PostedJob job={job}/>
              ))}
              
            </Box>
          </Grid>

          <Grid item lg={3} sm={3} sx={{ mt: '1.5%', ml: '0' ,backgroundColor: 'background.paper', borderRadius: '10px', boxShadow: "rgba(0, 0, 0, 0.10) 0px 5px 5px",}}>
            <Box>
              <JobsRightSide />
            </Box>
          </Grid>
        </Grid>
      </Box>
    </>
  );
};

export default Jobs;
