import React, {useState, useEffect } from "react";
import { Box, Grid, Typography, Button } from "@mui/material";
import Head from 'next/head'
import ChatSideBar from "../components/ChatSideBar";
import ChatArea from '../components/ChatArea'
import * as signalR from "@microsoft/signalr";
import {useRouter } from 'next/router'

const Messages = () => {

  const connection = new signalR.HubConnectionBuilder().withUrl("https://localhost:44369/message")
  .build();

  connection.start();
  const [message, setMessage] = useState();

  const Message=(props)=>{
    useEffect(()=>{
      props.connection.on("SendToReact",message=>{
        setMessage(message);
      })
    },[])
    
  }

  const router = useRouter()
  const {
    query: {loginUser}
  }  = router

  const props = {
    loginUser
  }
  console.log(props.loginUser)
  return (
    <>
      <Head>
        <title>Messages | Sera Job Po</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Box
        component="main"
        sx={{
          width: "100%",
          height: "100vh",
          backgroundColor: "background.paper",
          p: 3
        }}
      >
        <Message connection={connection}></Message>
        <Grid container spacing={4}>
          <Grid item lg={4} md={12} sm={12}>
                <ChatSideBar></ChatSideBar>
          </Grid>
          <Grid item lg={8} md={12} sm={12}>
            <ChatArea message={message}></ChatArea>
          </Grid>
        </Grid>
      </Box>
    </>
  );
};

export default Messages;
