import React, { useState, useEffect } from "react";
import { Box, Grid, Typography, Button } from "@mui/material";
import Head from "next/head";
import ChatSideBar from "../components/ChatSideBar";
import ChatArea from "../components/ChatArea";
import * as signalR from "@microsoft/signalr";
import { useRouter } from "next/router";
import { EmployerHeader } from "../components/EmployerHeader";
import axios from 'axios'

const Messages = () => {

  const router = useRouter();
  const {
    query: { postUser,loginUser },
  } = router;

  const props = {
    postUser,
    loginUser,
  };


  const connection = new signalR.HubConnectionBuilder()
    .withUrl("https://localhost:44369/ChatHub")
    .build();

    connection.start();
    
    const [messages, setMessages] = useState();
    connection.on("RecieveMessage", function(response){
      setMessages(response);
      console.log(response)
    });


    useEffect(()=>{

      axios.get("https://localhost:44369/GetAllChats")
      .then(function(res){
        setMessages(res.data)
      })
      .catch(function(res){
        console.log(res)
      })


      

    },[])
  
  

  return (
    <>
      <Head>
        <title>Messages | Sera Job Po</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Box
        component="main"
        sx={{
          width: "100%",
          height: "auto",
          backgroundColor: "background.paper",
        }}
      >
        <Grid container>
          <Grid item lg={12} md={12} sm={12}>
            <EmployerHeader />
          </Grid>
          <Grid container spacing={4} sx={{p:3}}>
            <Grid item lg={4} md={12} sm={12}>
              <ChatSideBar></ChatSideBar>
            </Grid>
            <Grid item lg={8} md={12} sm={12}>              
              <ChatArea messages={messages} connection={connection} loginUser={props.loginUser} postUser={postUser}></ChatArea>
            </Grid>
          </Grid>
        </Grid>
      </Box>
    </>
  );
};

export default Messages;
